
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.disksize.size = "40GB"
    config.vm.provider "virtualbox" do |v|
      v.name = "teste-docker"
      v.memory = 4096
      v.cpus = 2
    end
end
