apiVersion: apps/v1
kind: Deployment
metadata:
    name: 2rp-app-deployment
spec:
    template:
        metadata:
            name: node-app
            labels:
                app: node-app
            spec:
                containers:
                    - name: node-app-container
                      image: dockerdoshock/node-app:1.0
                      envFrom:
                        secretKeyRef:
                          name: var-
                          key: TWORPTEST
    replicas: 2
    selector:
        matchLabels:
            app: node-app
